# Generated by Django 5.1.3 on 2026-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_order_invoice_order_order_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date_ordered'], name='payment_ord_date_or_a129a0_idx'),
        ),
    ]
