# Generated by Django 5.1.3 on 2026-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_order_options_order_is_picked_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
