# Generated by Django 5.1.3 on 2025-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_type',
            field=models.CharField(default='apps', max_length=150),
            preserve_default=False,
        ),
    ]
