# Generated by Django 5.1.3 on 2025-03-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0002_menu_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('pasta', 'Pasta'), ('saute', 'Saute'), ('grill', 'Grill'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=150),
        ),
    ]
