# Generated by Django 5.1.3 on 2025-10-10 17:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0003_alter_menu_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('min_choices', models.PositiveIntegerField(default=0)),
                ('max_choices', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModfierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='MenuOrders.modifiergroup')),
            ],
            options={
                'ordering': ['group__sort_order', 'sort_order', 'id'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(blank=True, null=True)),
                ('min_choices', models.PositiveIntegerField(blank=True, null=True)),
                ('max_choices', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_group', to='MenuOrders.menu')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MenuOrders.modifiergroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('menu', 'group')},
            },
        ),
    ]
