# Generated by Django 5.1.3 on 2025-10-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0004_modifiergroup_modfieroption_menumodifiergroup'),
    ]

    operations = [
        migrations.RenameModel("ModfierOption", "ModifierOption"),
    ]
