# Generated by Django 5.2.7 on 2025-10-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0005_rename_modfieroption_to_modifieroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
