# Generated by Django 5.2.7 on 2025-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0006_alter_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(upload_to='menu_pics/'),
        ),
    ]
