# Generated by Django 5.1.3 on 2026-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0007_alter_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('salad', 'Salad'), ('pasta', 'Pasta'), ('saute', 'Saute'), ('grill', 'Grill'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=150),
        ),
    ]
