# Generated by Django 5.2.7 on 2026-07-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0008_alter_menu_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='MenuOrders.menu')),
            ],
            options={
                'unique_together': {('menu', 'alias')},
            },
        ),
    ]
