# Generated by Django 5.2.7 on 2026-07-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0009_menualias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='MenuOrders.dietarytag'),
        ),
    ]
