# Generated by Django 5.2.7 on 2026-08-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0010_dietarytag_menu_dietary_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('salad', 'Salad'), ('pasta', 'Pasta'), ('saute', 'Saute'), ('parms', 'Parms'), ('grill', 'Grill'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=150),
        ),
    ]
