# Generated by Django 5.2.7 on 2026-08-05 16:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuOrders', '0011_alter_menu_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieroption',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
    ]
